version: "3.8" # describe available feature for this version
services: # list of containers, names it's up to you
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    env_file: # with env files
      - ./env/mongo.env
    container_name: mongodb # othervise, the name of the container will be {project_folder_name_service_name}
#   networks: # if you would like to have a specifically named network.
      #- goals-net 
  backend:
    build: ./backend # build service based on Dockerfile
    ports:
      - '90:90' # host port:container internal port
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on: 
      - mongodb
  frontend:
    build: ./frontend
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true # open input connection. = -it flag (interaction mode)
    tty: true # attach terminal. = -it flag (interaction mode)
    depends_on: 
      - backend
volumes: # docker should be aware of what volumes it should create for your services 
  data:
  logs: