version: "3.8" # describe available feature for this version
services: # list of containers, names it's up to you
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    env_file: # with env files
      - ./env/mongo.env
     # if you would like to have a specifically named network.
#    networks:
      #- goals-net 
  backend:
    build: ./backend # build service based on Dockerfile
    ports:
      - '90:90' # host port:container internal port
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on: 
      - mongodb
#  frontend:

# docker should be aware of what volumes it should create for your services 
volumes: 
  data:
  logs: